=== fabiansep/MTI476/parte2/laQuena/public/docs/bodega.dtd
<!ELEMENT bodega 		(	establecimiento,
							productos
							)>
<!ELEMENT establecimiento			  		(#PCDATA)>
<!ELEMENT productos		  		(producto*)>
<!ELEMENT producto			  		(stock,price)>
<!ELEMENT stock				(#PCDATA)>
<!ELEMENT price				(value,currency)>

<!ELEMENT value			  		(#PCDATA)>
<!ELEMENT currency			  		(#PCDATA)>

<!--atributos establecimiento-->
<!ATTLIST establecimiento 	establecimientoId 	CDATA #REQUIRED>

<!--atributos producto-->
<!ATTLIST producto 		  	productoID	CDATA #REQUIRED>
<!ATTLIST producto  		  	name	CDATA #REQUIRED>

=== fabiansep/MTI476/parte2/laQuena/public/docs/bodega.xml
<!DOCTYPE precio SYSTEM "bodega.dtd">
<bodega>
    <establecimiento establecimientoId='1'>La Quena Valdivia</establecimiento>
    <productos>
        <producto productoID='10' name='Zampoñaaa'>
            <stock>70</stock>
            <price>
                <value>65000</value>
                <currency>CLP</currency>
            </price>
        </producto>
				<producto productoID='10' name='Zampoñaaa'>
            <stock>70</stock>
            <price>
                <value>65000</value>
                <currency>CLP</currency>
            </price>
        </producto>				
    </productos>
</bodega>
