=== fabiansep/MTI476/parte1/producto.dtd
<!ELEMENT producto 		(	name,
							country,
							geo?,
							history,
							clasificationList,
							height,
							weight

							)>
<!ELEMENT name			  		(#PCDATA)>
<!ELEMENT country		  		(#PCDATA)>
<!ELEMENT geo			  		(latitude,longitude)>
<!ELEMENT history				(#PCDATA)>
<!ELEMENT clasificationList		(clasification*)>
<!ELEMENT height				(value,unitCode)>
<!ELEMENT weight				(value,unitCode)>

<!--atributos producto-->
<!ATTLIST producto 	idProduct 	CDATA #REQUIRED>
<!--atributos country-->
<!ATTLIST country 		  	iso31661Code	CDATA #REQUIRED>
<!--elementos de geo-->
<!ELEMENT latitude			(#PCDATA)>
<!ELEMENT longitude			(#PCDATA)>
<!--elementos de clasificationList-->
<!ELEMENT clasification		(#PCDATA)>
<!--elementos de height-->
<!ELEMENT value				(#PCDATA)>
<!ELEMENT unitCode			(#PCDATA)>

=== fabiansep/MTI476/parte1/producto.xml
<!DOCTYPE producto SYSTEM "producto.dtd">
<producto	idProduct = "12331">
	<name>Charango</name>
    <country iso31661Code="CL">Chile</country>
	<geo>
		<latitude>-33.441027</latitude>
		<longitude>-70.65346</longitude>
	</geo>	
	<history>El charango es un instrumento de cuerda principalmente usado en la regi칩n de la cordillera de los Andes, con origen en la regi칩n del altiplano andino. Posee cinco cuerdas dobles, aunque hay variaciones con menos o m치s cuerdas, pero casi siempre en cinco 칩rdenes o juegos.</history>
	<clasificationList>
		<clasification>Instrumento de Cuerda</clasification>
		<clasification>Instrumento de Cuerda pulsada</clasification>
	</clasificationList>
	<height>
		<value>30</value>
		<unitCode>CM</unitCode>
	</height>
	<weight>
		<value>1</value>
		<unitCode>KG</unitCode>		
	</weight>
</producto>
